### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Findoss** [Findoss/Electro-Resurs#1]
* [x] оптимизация картинок
* [x] мобильное меню
* [x] мобильная верстка блоков
* [ ] форма обратной связи ?
* [x] сео для поисковика
* [x] сео для ссылок в Соц сетях
* [ ] кнопка подробнее у эл. щитов
* [ ] анимации скрола
* [ ] анимации кнопок
* [x] регистрация в Яндекс Карте
* [x] регистрация в Яндекс Справочнике
* [ ] назначение клавиш и порядок перехода на tab
* [ ] установить роли для элементов
* [ ] перевод картинок на webP
